# Numpy-Log

In [1]:
import numpy as np

In [3]:
np.log(10)

2.302585092994046

In [4]:
np.log(1)

0.0

In [5]:
np.log10(10)

1.0

In [9]:
np.log10(2)

0.3010299956639812

In [8]:
np.log10(3)

0.47712125471966244

In [10]:
np.log2(10)

3.321928094887362

In [11]:
np.log10(23)

1.3617278360175928

In [12]:
arr = np.array([10,20,30,40,50])
np.log(arr)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301])

In [13]:
np.log2(arr)

array([3.32192809, 4.32192809, 4.9068906 , 5.32192809, 5.64385619])

In [14]:
np.log10(arr)

array([1.        , 1.30103   , 1.47712125, 1.60205999, 1.69897   ])

In [15]:
data = [1,2,3,4,5,6,7,8,9,10]
np.log(data)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])